### ISSUE TITLE
uninitialized constant SlackRubyBotServer::Stripe::Commands::SlackRubyBot

### ISSUE THREAD

**Issue by duffn** [slack-ruby/slack-ruby-bot-server-stripe#9]
Running tests locally results in the following error in a number of different endpoints.

```
$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin20]
```

```
$ DATABASE_ADAPTER=mongoid bundle install
$ DATABASE_ADAPTER=mongoid bundle exec rake spec
```

```
An error occurred while loading ./spec/slack-ruby-bot-server-stripe/api/endpoints/subscriptions_endpoint_spec.rb.
Failure/Error:
  class Subscription < SlackRubyBot::Commands::Base
    command 'subscription' do |client, data, _match|
      team = ::Team.find(client.owner.id)
      include_admin_info = (data.user == team.activated_user_id)
      client.say(channel: data.channel, text: team.subscription_text(include_admin_info: include_admin_info))
      logger.info "SUBSCRIPTION: #{client.owner} - #{data.user}"
    end

NameError:
  uninitialized constant SlackRubyBotServer::Stripe::Commands::SlackRubyBot
# ./lib/slack-ruby-bot-server-stripe/commands/subscription.rb:6:in `<module:Commands>'
# ./lib/slack-ruby-bot-server-stripe/commands/subscription.rb:5:in `<module:Stripe>'
# ./lib/slack-ruby-bot-server-stripe/commands/subscription.rb:4:in `<module:SlackRubyBotServer>'
# ./lib/slack-ruby-bot-server-stripe/commands/subscription.rb:3:in `<top (required)>'
# ./lib/slack-ruby-bot-server-stripe/commands.rb:3:in `require_relative'
# ./lib/slack-ruby-bot-server-stripe/commands.rb:3:in `<top (required)>'
# ./lib/slack-ruby-bot-server-stripe.rb:13:in `require_relative'
# ./lib/slack-ruby-bot-server-stripe.rb:13:in `<top (required)>'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./spec/slack-ruby-bot-server-stripe/api/endpoints/subscriptions_endpoint_spec.rb:3:in `require'
# ./spec/slack-ruby-bot-server-stripe/api/endpoints/subscriptions_endpoint_spec.rb:3:in `<top (required)>'
```

**Comment by dblock** [comment]
The RTM part of slack-ruby-bot-server gem was split into slack-ruby-bot-server-rtm. I PRed https://github.com/slack-ruby/slack-ruby-bot-server-stripe/pull/13 which fixes most things, so you can use that.

The RTM bots are deprecated by slack in favor of event-based ones, so anything with -rtm in it is quickly becoming legacy. I do have half a dozen bots that use it though, I don't have the bandwidth to rewrite them completely.

**Comment by duffn** [comment]
Thanks. I've opened the PR at https://github.com/slack-ruby/slack-ruby-bot-server-stripe/pull/14
